# Generated by Django 5.2.8 on 2025-11-09 14:38

import Management_App.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Extra_Details',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('FE', 'Female'), ('MA', 'Male'), ('CU', 'Custom')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[Management_App.models.validate_age])),
            ],
        ),
    ]
