# Generated by Django 5.2.8 on 2025-11-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title_post', models.CharField(max_length=200)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_likes', models.DecimalField(decimal_places=0, default=0, max_digits=9999, max_length=9, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
