# Generated by Django 5.2.8 on 2025-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_App', '0002_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='post_views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9999, max_length=9, null=True),
        ),
    ]
