# Generated by Django 5.2.8 on 2025-11-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_App', '0004_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_extra_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
